apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/part-of: gitops-control-plane
    platform.hashicorp.com/phase: "3"
spec:
  description: Platform components managed by Argo CD.
  sourceRepos:
    - https://github.com/Leninfitfreak/Vault.git
    - https://helm.releases.hashicorp.com
  destinations:
    - server: https://kubernetes.default.svc
      namespace: vault
    - name: vault-dr
      namespace: vault
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: StatefulSet
    - group: policy
      kind: PodDisruptionBudget
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
